base_path: /home/winxp5421/ProbablyNotAHacker.com
blurb_max: 50
date_format: '%Y-%m-%d'
home_page: README
markdown_exts:
- codehilite
- toc
- pykwiki.ext.tpl
- pykwiki.ext.post
postlist:
  max_pages: 5
  order_field: mtime
  order_type: descending
  per_page: 2
  post_type: preview
rss_max_entries: 20
site:
  author: winxp5421
  base_url: 'https://www.probablynotahacker.com/'
  description: I am not really sure what this is to be honest. The general idea behind this is a community wiki.
  keywords: 
  title: Probablynotahacker.com
source_dir: source
source_ext: .md
style: dark
target_dir: docroot
theme: null
time_format: '%H:%M:%S'
timestamp_format: '%Y-%m-%d %H:%M'
upload_exts:
- .gif
- .jpg
- .jpeg
- .png
- .tiff
- .pdf
version: 2
web_prefix: ''
